CREATE TABLE auditoria (;
    ID I(4),;
    TABLA CHAR(50),;
    OPERACION CHAR(10),;
    CAMPOS MEMO,;
    FECHA DATETIME,;
    PROCESADO LOGICAL;
)

CREATE TABLE mapeo (;
    TABLA_VFP CHAR(100),;
    CAMPO_VFP CHAR(100),;
    TABLA_MYSQL CHAR(100),;
    CAMPO_MYSQL CHAR(100),;
    CLAVE LOGICAL,;
    PONER_VALOR CHAR(150),;
    PONER_FUNCION CHAR(150),;
    COMENTARIO CHAR(200);
)

INSERT INTO mapeo VALUES ('depósitos', 'num', 'abm_depositos', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'nombre', 'abm_depositos', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'direccion', 'abm_depositos', 'domicilio', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'tipo', 'abm_depositos', 'descripcion', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'predet1', 'abm_depositos', 'predeterminado', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'propio', 'abm_depositos', 'id_abm_tipos_de_propietario', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'idcliente', 'abm_depositos', 'id_abm_clientes', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'clasificacion', 'abm_depositos', 'clasificacion', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'serial', 'abm_articulo_univoco', 'serial', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'rfid', 'abm_articulo_univoco', 'rfid', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'codbar', 'abm_articulo_univoco', 'codbar', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'numdep', 'abm_articulo_univoco', 'id_abm_depositos', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'numdep_actual', 'abm_articulo_univoco', 'id_abm_depositos_actual', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'numartic', 'abm_articulo_univoco', 'id_abm_articulos', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'activo', .F., '', '0', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'identificados', 'abm_articulo_univoco', 'identificados', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'id_usuario', 'abm_articulo_univoco', 'id_abm_empleados_del_cliente', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'id_abm_clientes', .F., '', '0', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'articulo_propio', .F., '', '1', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'tipo_comprobante_ultimo', 'abm_articulo_univoco', 'id_abm_tipos_de_comprobante_ultimo', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'numero_comprobante_ultimo', 'abm_articulo_univoco', 'numero_comprobante_ultimo', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'ultima_lectura', 'abm_articulo_univoco', 'ultima_lectura', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'sincronizar', .F., '', '1', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'observaciones', 'abm_articulo_univoco', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', 'ids', 'abm_articulo_univoco', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('articulo_univoco1', '', 'abm_articulo_univoco', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('depósitos', 'propiet', 'abm_depositos', 'codigo', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'deposito_subdeposito', 'abm_depositos', 'id_abm_tipos_de_deposito', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', 'idgeneral', 'abm_depositos', 'id_abm_empleados_del_cliente', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('depósitos', '', 'abm_depositos', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('depósitos', 'idgeneral', 'abm_depositos', 'id_abm_empleados_del_cliente', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'legajo', 'abm_empleados_del_cliente', 'legajo', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'nombre', 'abm_empleados_del_cliente', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'idcliente', 'abm_empleados_del_cliente', 'id_abm_clientes', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'fecha_ingreso', 'abm_empleados_del_cliente', 'fecha_de_ingreso', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'fecha_chip', 'abm_empleados_del_cliente', 'fecha_de_chipeo', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'cargo', 'abm_empleados_del_cliente', 'cargo', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'prendas_asigandas', 'abm_empleados_del_cliente', 'cantidad_de_prendas_asignadas', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'imagen', 'abm_empleados_del_cliente', 'imagen', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'huella_dactilar', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'codigo_saco1', 'abm_empleados_del_cliente', 'codigo_saco_1', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'codigo_saco2', 'abm_empleados_del_cliente', 'codigo_saco_2', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'activo', .F., '', '0', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'id_abm_set_de_prendas', .F., '', '0', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'codigo', .F., '', 'CodigoAutomatico("abm_empleados_del_cliente")', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'domicilio', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'numero_casillero', 'abm_empleados_del_cliente', 'numero_casillero', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'talla', 'abm_empleados_del_cliente', 'talla', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'sexo', 'abm_empleados_del_cliente', 'sexo', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'color_uniforme', 'abm_empleados_del_cliente', 'color_uniforme', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'deja_ropa', 'abm_empleados_del_cliente', 'deja_ropa', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'articulo1', 'abm_empleados_del_cliente', 'articulo1', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'cantidad1', 'abm_empleados_del_cliente', 'cantidad1', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'estado1', 'abm_empleados_del_cliente', 'estado1', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'articulo2', 'abm_empleados_del_cliente', 'articulo2', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'cantidad2', 'abm_empleados_del_cliente', 'cantidad2', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'estado2', 'abm_empleados_del_cliente', 'estado2', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'articulo3', 'abm_empleados_del_cliente', 'articulo3', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'cantidad3', 'abm_empleados_del_cliente', 'cantidad3', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'estado3', 'abm_empleados_del_cliente', 'estado3', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'articulo4', 'abm_empleados_del_cliente', 'articulo4', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'cantidad4', 'abm_empleados_del_cliente', 'cantidad4', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'estado4', 'abm_empleados_del_cliente', 'estado4', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'articulo5', 'abm_empleados_del_cliente', 'articulo5', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'cantidad5', 'abm_empleados_del_cliente', 'cantidad5', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'estado5', 'abm_empleados_del_cliente', 'estado5', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'codigo_electronico', 'abm_empleados_del_cliente', 'codigo_electronico', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('empleados_cliente', 'id', 'abm_empleados_del_cliente', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('empleados_cliente', '', 'abm_empleados_del_cliente', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('clientes', 'codigo', 'abm_clientes', 'codigo', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'nombre', 'abm_clientes', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'marca', 'abm_clientes', 'nombre_de_fantasia', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'dirección', 'abm_clientes', 'domicilio', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'lugar_entrega', 'abm_clientes', 'domicilio_de_entrega', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'marca', 'abm_clientes', 'domicilio_de_facturacion', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'cód_postal', 'abm_clientes', 'codigo_postal', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_localidades', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_provincias', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_ciudades', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_municipios', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', 'cedula', 'abm_clientes', 'documento', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_regiones_1', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', 'nacim', 'abm_clientes', 'fecha_de_nacimiento', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'cuit', 'abm_clientes', 'clave_impositiva', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'teléfono', 'abm_clientes', 'telefono_1', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'teléfono2', 'abm_clientes', 'telefono_2', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'teléfono3', 'abm_clientes', 'telefono_3', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'num_radio', 'abm_clientes', 'radio', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'fax', 'abm_clientes', 'fax', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'mail', 'abm_clientes', 'email', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'contacto', 'abm_clientes', 'contacto_1', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'cargo_1', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'mail_2', 'abm_clientes', 'email_1', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'persona_contacto', 'abm_clientes', 'contacto_2', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'cargo_contacto', 'abm_clientes', 'cargo_2', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'mail_3', 'abm_clientes', 'email_2', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'contacto_3', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'cargo_3', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'email_3', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'website', 'abm_clientes', 'website', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'comentarios', 'abm_clientes', 'logo_cliente', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_calificacion_de_clientes', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_categoria_impositiva', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', 'retefuente', 'abm_clientes', 'retencion_fuente', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'reteiva', 'abm_clientes', 'retencion_iva', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', 'reteica', 'abm_clientes', 'retencion_ica', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_asientos_automaticos_ventas', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_cuentas_contables', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_politica_de_precios_articulos', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_politica_de_precios_servicios', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'activo', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('clientes', 'idcliente', 'abm_clientes', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('clientes', '', 'abm_clientes', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'codigo', .F., '', 'CodigoAutomatico("abm_talles")', '')
INSERT INTO mapeo VALUES ('unidmedida', 'unidmedida', 'abm_talles', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('unidmedida', 'ids', 'abm_talles', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_talles', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'codigo', .F., '', 'CodigoAutomatico("abm_rubros")', '')
INSERT INTO mapeo VALUES ('rubro', 'rubro', 'abm_rubros', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('rubro', 'ids', 'abm_rubros', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'codigo', .F., '', 'CodigoAutomatico("abm_subrubros")', '')
INSERT INTO mapeo VALUES ('subrubro', 'subrubro', 'abm_subrubros', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('subrubro', 'ids', 'abm_subrubros', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'codigo', .F., '', 'CodigoAutomatico("abm_unidades_de_medida")', '')
INSERT INTO mapeo VALUES ('unidmedida', 'unidmedida', 'abm_unidades_de_medida', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('unidmedida', 'ids', 'abm_unidades_de_medida', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('unidmedida', '', 'abm_unidades_de_medida', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'codigo', .F., '', 'CodigoAutomatico("abm_colores")', '')
INSERT INTO mapeo VALUES ('colores', 'nombre', 'abm_colores', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('colores', 'idsql', 'abm_colores', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('colores', '', 'abm_colores', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', 'codigo', 'abm_articulos', 'codigo', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'detalle', 'abm_articulos', 'nombre', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'item', 'abm_articulos', 'codigo_de_barras', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_rubros', .F., '', 'SQL_oDb_funcion_ID('ABM_Rubros', ObtenerValorClave(cTablaVfp, cJason, "RUBRO"))', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_subrubros', .F., '', 'SQL_oDb_funcion_ID('ABM_Subrubros', ObtenerValorClave(cTablaVfp, cJason, "SUBRUBRO"))', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_unidades_de_medida', .F., '', 'SQL_oDb_funcion_ID('ABM_Unidades_de_Medida', ObtenerValorClave(cTablaVfp, cJason, "UNMEDIDA"))', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_colores', .F., '', 'SQL_oDb_funcion_ID('ABM_colores', ObtenerValorClave(cTablaVfp, cJason, "COLOR"))', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_talles', .F., '', 'SQL_oDb_funcion_ID('ABM_talles', ObtenerValorClave(cTablaVfp, cJason, "UNMEDIDA"))', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_proveedores', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', 'pcosto', 'abm_articulos', 'precio_de_costo', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'impinter', 'abm_articulos', 'impuestos_internos', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'stock_minimo', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'stock_maximo', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_cuentas_contables_compras', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_cuentas_contables_ventas', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_centros_de_costo_compras', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_centros_de_costo_ventas', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', 'rotacion', 'abm_articulos', 'criterio_de_rotacion', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'peso_seco', 'abm_articulos', 'peso_seco', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'peso_seco_error', 'abm_articulos', 'peso_seco_cota_de_error', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'peso_humedo', 'abm_articulos', 'peso_humedo', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'peso_humero_error', 'abm_articulos', 'peso_humedo_cota_de_error', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'imagen', 'abm_articulos', 'imagen', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', 'observac', 'abm_articulos', 'observaciones', .F., '', '', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'activo', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'datetime', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'ultimo_cambio', .F., '=DATETIME()', '', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'eliminado', .F., '', '0', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'ui', .F., '', '_sincroaui', '')
INSERT INTO mapeo VALUES ('stock1', 'num', 'abm_articulos', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('stock1', '', 'abm_articulos', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('rubro', '', 'abm_rubros', 'id', .F., '', '0', '')
INSERT INTO mapeo VALUES ('subrubro', '', 'abm_subrubros', 'id', .F., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_tipos_de_comprobante', .F., '', 'SQL_oDb_funcion_ID('ABM_tipos_de_comprobante', ObtenerValorClave(cTablaVfp, cJason, "TIPO_COMPROBANTE"))', '')
INSERT INTO mapeo VALUES ('remi1', 'fechahora', 'documentos_cabecera', 'fecha_hora', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_estados', .F., '', 'SQL_oDb_funcion_ID('ABM_estados', ObtenerValorClave(cTablaVfp, cJason, "ESTADO"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_monedas', .F., '', '_sincromoneda', '')
INSERT INTO mapeo VALUES ('remi1', 'numero', 'documentos_cabecera', 'numero', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'codigo_documento', .F., '', 'SQL_oDb_funcion_COD('ABM_tipos_de_comprobante', ObtenerValorClave(cTablaVfp, cJason, "TIPO"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_clientes', .F., '', 'SQL_oDb_funcion_ID('ABM_clientes', ObtenerValorClave(cTablaVfp, cJason, "IDCLIENTE"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_usuarios_responsable_de_caja', .F., '', 'SQL_oDb_funcion_ID('ABM_usuarios_cabecera', ObtenerValorClave(cTablaVfp, cJason, "VENDEDOR"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_usuarios_entrega_fuera_del_turno', .F., '', 'SQL_oDb_funcion_ID('ABM_usuarios_cabecera', ObtenerValorClave(cTablaVfp, cJason, "VENDEDOR1"))', '')
INSERT INTO mapeo VALUES ('remi1', 'impfact', 'documentos_cabecera', 'id_abm_usuarios_responsable_recepcion', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_usuarios_responsable_entrega', .F., '', 'SQL_oDb_funcion_ID('ABM_usuarios_cabecera', ObtenerValorClave(cTablaVfp, cJason, "MTOENTREGA"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_usuarios_responsable_conteo', .F., '', 'SQL_oDb_funcion_ID('ABM_usuarios_cabecera', ObtenerValorClave(cTablaVfp, cJason, "RESPONSABLE"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_condiciones_de_venta', .F., '', 'SQL_oDb_funcion_ID('ABM_usuarios_cabecera', ObtenerValorClave(cTablaVfp, cJason, "CONDVTA"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_medios_de_pago', .F., '', 'SQL_oDb_funcion_ID('ABM_usuarios_cabecera', ObtenerValorClave(cTablaVfp, cJason, "FORMAPAGO"))', '')
INSERT INTO mapeo VALUES ('remi1', 'estad2', 'documentos_cabecera', 'id_abm_descuentos_parametrizados', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'bonificaci', 'documentos_cabecera', 'bonificacion', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'retefuente', 'documentos_cabecera', 'retencion_fuente', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'reteiva', 'documentos_cabecera', 'retencion_iva', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'reteica', 'documentos_cabecera', 'retencion_ica', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'total', 'documentos_cabecera', 'total', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'saldo', 'documentos_cabecera', 'saldo', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'entregado', 'documentos_cabecera', 'entregado', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'pagado', 'documentos_cabecera', 'pagado', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'facturado', 'documentos_cabecera', 'facturado', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'imp1', 'documentos_cabecera', 'impreso', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'dateimp', 'documentos_cabecera', 'impreso_en_fecha', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'cantidad_total_servicios', .F., '', '0', 'calcular la cantidad total en remi2')
INSERT INTO mapeo VALUES ('remi1', 'cantserv', 'documentos_cabecera', 'cantidad_servicios_restante', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'subprocesos', 'documentos_cabecera', 'cantidad_total_subprocesos', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'subprocesos_pendientes', 'documentos_cabecera', 'cantidad_subprocesos_restante', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'entrega', 'documentos_cabecera', 'entregado_en_fecha', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'bajado_en', 'documentos_cabecera', 'refundido_en', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'contiene_muestras', .F., '', 'ObtenerValorClave(cTablaVfp, cJason, "CONTIENE_MUESTRAS")', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'anulado', .F., '', 'ObtenerValorClave(cTablaVfp, cJason, "ANULADA")', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'fecha_de_definicion', .F., '', 'IIF(EMPTY(ObtenerValorClave(cTablaVfp, cJason, "MTOENTREGA2")),{},ObtenerValorClave(cTablaVfp, cJason, "MTOENTREGA2"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'fecha_de_entrega', .F., '', 'ObtenerValorClave(cTablaVfp, cJason, "ENTREGA1")', '')
INSERT INTO mapeo VALUES ('remi1', 'ftp', 'documentos_cabecera', 'fecha_de_cobranza', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_depositos_almacen_origen', .F., '', 'SQL_oDb_funcion_ID('ABM_depositos', ObtenerValorClave(cTablaVfp, cJason, "DEP_ORIG"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_depositos_almacen_destino', .F., '', 'SQL_oDb_funcion_ID('ABM_depositos', ObtenerValorClave(cTablaVfp, cJason, "DEP_DEST"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_depositos_almacen_de_entrega', .F., '', 'SQL_oDb_funcion_ID('ABM_depositos', ObtenerValorClave(cTablaVfp, cJason, "DEP_DEST"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_transportistas', .F., '', 'SQL_oDb_funcion_ID('ABM_transportistas', ObtenerValorClave(cTablaVfp, cJason, "TRANSPENV"))', '')
INSERT INTO mapeo VALUES ('remi1', 'npos', 'documentos_cabecera', 'comprobante_manual', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'sin_definir', .F., '', 'ObtenerValorClave(cTablaVfp, cJason, "SIN_DEFINIR")', '')
INSERT INTO mapeo VALUES ('remi1', 'status', 'documentos_cabecera', 'estado', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'orden_de_corte', 'documentos_cabecera', 'orden_de_corte', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'remito_del_cliente', 'documentos_cabecera', 'remito_del_cliente', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'kilos', 'documentos_cabecera', 'peso_kilos', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', 'muestra', 'documentos_cabecera', 'id_abm_muestras', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'abm_justificaciones_movimientos_asimetricos', .F., '', 'SQL_oDb_funcion_ID('ABM_Justificaciones_movimientos_asimetricos', ObtenerValorClave(cTablaVfp, cJason, "TALLER"))', '')
INSERT INTO mapeo VALUES ('remi1', 'enplanta', 'documentos_cabecera', 'envio_a_domicilio', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_responsable_de_cobranza', .F., '', 'SQL_oDb_funcion_ID('ABM_usuarios_cabecera', ObtenerValorClave(cTablaVfp, cJason, "ESTADO"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'exportado', .F., '', 'ObtenerValorClave(cTablaVfp, cJason, "EXPORTADO")', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_leyendas1', .F., '', 'SQL_oDb_funcion_ID('ABM_leyendas', ObtenerValorClave(cTablaVfp, cJason, "LEYENDA1"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_leyendas2', .F., '', 'SQL_oDb_funcion_ID('ABM_leyendas', ObtenerValorClave(cTablaVfp, cJason, "LEYENDA2"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_leyendas3', .F., '', 'SQL_oDb_funcion_ID('ABM_leyendas', ObtenerValorClave(cTablaVfp, cJason, "LEYENDA3"))', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id_abm_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('remi1', '', 'documentos_cabecera', 'id', .F., '', '0', '')
INSERT INTO mapeo VALUES ('remi2', 'num', 'documentos_contenido', 'id_documentos_cabecera', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'cantant', 'documentos_contenido', 'cantidad_anterior', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id_ABM_servicios', .F., '', 'SQL_oDb_funcion_ID('ABM_servicios_de_venta', ObtenerValorClave(cTablaVfp, cJason, "NUMSERV"))', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id_ABM_articulos', .F., '', 'SQL_oDb_funcion_ID('ABM_articulos', ObtenerValorClave(cTablaVfp, cJason, "NUMARTIC"))', '')
INSERT INTO mapeo VALUES ('remi2', 'cantidad', 'documentos_contenido', 'cantidad', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'cantidad_actual', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'piezas', 'documentos_contenido', 'piezas', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'precio', 'documentos_contenido', 'neto', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'impuestos', .F., '', '0', 'nimplinea - (precio * cantidad)')
INSERT INTO mapeo VALUES ('remi2', 'bonific', 'documentos_contenido', 'descuentos', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'recargos', .F., '', '0', '')
INSERT INTO mapeo VALUES ('remi2', 'nimplinea', 'documentos_contenido', 'total', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'sub1', 'documentos_contenido', 'relacion_subproceso', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'condesc', 'documentos_contenido', 'valor_arbitrario', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'ftp', 'documentos_contenido', 'fecha_entrega_parcial', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'fechoraenv', 'documentos_contenido', 'fecha_hora_envio', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'fechahorarec', 'documentos_contenido', 'fecha_hora_recepcion', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'kilos_metros', 'documentos_contenido', 'kilos_metros', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'prioridad', 'documentos_contenido', 'prioridad', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id_estado', .F., '', 'SQL_oDb_funcion_ID('ABM_estados', ObtenerValorClave(cTablaVfp, cJason, "ESTADO"))', '')
INSERT INTO mapeo VALUES ('remi2', 'comenzar', 'documentos_contenido', 'comenzado', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'terminado', 'documentos_contenido', 'terminado', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id_responsable', .F., '', 'SQL_oDb_funcion_ID('ABM_usuarios_cabecera', ObtenerValorClave(cTablaVfp, cJason, "AUTORIZOENV"))', '')
INSERT INTO mapeo VALUES ('remi2', 'sub10', 'documentos_contenido', 'cantidad_original_en_OT', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'sub6', 'documentos_contenido', 'ID_documentos_contenido_ENVIO', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'orden_impresion', 'documentos_contenido', 'orden_de_impresion', .F., '', '', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'version', .F., '=version + 1', '', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id_ABM_empresas', .T., '', '_sincroaempresa', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id_ABM_regiones', .F., '', '_sincroaregion', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id_ABM_usuarios', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id_ABM_ultimo_usuario', .F., '', '_sincroausuario', '')
INSERT INTO mapeo VALUES ('remi2', '', 'documentos_contenido', 'id', .F., '', '0', '')
INSERT INTO mapeo VALUES ('remi1', 'num', 'documentos_cabecera', 'sincronizacion', .T., '', '', '')
INSERT INTO mapeo VALUES ('remi2', 'num', 'documentos_contenido', 'sincronizacion', .T., '', '', '')

